name: Build URI Handler

on: push

jobs:
  buildWindows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2.3.0

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.7

      - name: Compile
        run: haxe build.hxml

      - name: Publish Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windowsBuild
          path: export/bin

  buildLinux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.0

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.7

      - name: Compile
        run: |
          haxe build.hxml

      - name: Publish Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linuxBuild
          path: export/bin
